name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.2]
        symfony: [5.4.*, 6.2.*]
        dependency-version: [prefer-lowest, prefer-stable]

    name: Tests P${{ matrix.php }} - SF${{ matrix.symfony }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-SF${{ matrix.symfony }}-${{ matrix.dependency-version }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, mbstring, zip
          coverage: none

      - name: Require Symfony Version
        run: >
          composer require
          "symfony/config:${{ matrix.symfony }}"
          "symfony/dependency-injection:${{ matrix.symfony }}"
          "symfony/http-kernel:${{ matrix.symfony }}"
          --no-interaction --no-update
      - name: Install Composer dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Integration Tests
        run: php ./vendor/bin/simple-phpunit
